-- create
CREATE TABLE T_CARS(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    marke VARCHAR2(50) NOT NULL,
    modell VARCHAR2(50) NOT NULL,
    ausstattung VARCHAR2(100) NOT NULL
);

-- empty table
DELETE T_CARS;

-- insert
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('VW', 'Jetta', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Mercedes', 'A45 AMG', 'Mittelklasse');
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Mercedes', 'C63', 'Minimale Ausstatung');
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Audi', 'A8', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Ford', 'Focus', 'Mittelklasse');
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('VW', 'Polo', 'Mittelklasse');
