-- create
CREATE TABLE T_CARS(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    marke VARCHAR2(50) NOT NULL,
    modell VARCHAR2(50) NOT NULL,
    ausstattung VARCHAR2(100) NOT NULL
);

-- empty table
DELETE T_CARS;

-- insert
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (1,'VW', 'Jetta', 'Vollaustattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (2,'Mercedes', 'A45 AMG', 'Mittelklasse');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (3,'Mercedes', 'C63', 'Minimale Ausstattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (4,'Audi', 'A8', 'Vollaustattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (5,'Ford', 'Focus', 'Mittelklasse');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (6,'VW', 'Polo', 'Mittelklasse');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (7,'VW', 'Golf', 'Vollaustattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (8,'Audi', 'R8', 'Vollaustattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (9,'Mini', 'Cooper', 'Minimale Ausstattung');
INSERT INTO T_CARS (id, marke, modell, ausstattung) VALUES (10,'Tesla', 'Model X', 'Vollaustattung');
