-- drop old tables
DROP TABLE T_BUCHUNGEN CASCADE CONSTRAINTS;
DROP TABLE T_STANDORTE CASCADE CONSTRAINTS;
DROP TABLE T_KUNDEN CASCADE CONSTRAINTS;
DROP TABLE T_MITARBEITER CASCADE CONSTRAINTS;
DROP TABLE T_PREISE CASCADE CONSTRAINTS;
DROP TABLE T_SCHAEDEN CASCADE CONSTRAINTS;
DROP TABLE T_VERFUEGBARKEIT CASCADE CONSTRAINTS;
DROP TABLE T_CARS CASCADE CONSTRAINTS;
DROP TABLE T_PERSONEN CASCADE CONSTRAINTS;
DROP TABLE T_ADRESSEN CASCADE CONSTRAINTS;

/* --------------------
   T_ADRESSEN
*/ --------------------

-- create
CREATE TABLE T_ADRESSEN(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strasse VARCHAR2(128) NOT NULL,
    hausnummer VARCHAR2(4) NOT NULL,
    plz VARCHAR2(4) NOT NULL,
    ort VARCHAR2(28) NOT NULL
);

-- empty table
DELETE T_ADRESSEN;

-- insert
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Bernardgasse', '333', '1070', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Thaliastrasse', '333', '1160', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Hochstaedtplatz', '333', '1200', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Einoedhofweg', '333', '8042', 'Graz');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Salzachstrasse', '333', '1200', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Adalbert-Stifter-Strasse', '333', '1200', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Mariahilferstrasse', '333', '1060', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Lerchengasse', '333', '1010', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Neubaugasse', '333', '1020', 'Wien');
INSERT INTO T_ADRESSEN (strasse, hausnummer, plz, ort) VALUES ('Almdudlergasse', '333', '1040', 'Wien');

/* --------------------
   T_CARS
*/ --------------------

-- create
CREATE TABLE T_CARS(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marke VARCHAR2(50) NOT NULL,
    modell VARCHAR2(50) NOT NULL,
    ausstattung VARCHAR2(100) NOT NULL
);

-- empty table
DELETE T_CARS;

-- insert
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('VW', 'Jetta', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Mercedes', 'A45 AMG', 'Mittelklasse');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Mercedes', 'C63', 'Minimale Ausstattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Audi', 'A8', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Ford', 'Focus', 'Mittelklasse');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('VW', 'Polo', 'Mittelklasse');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('VW', 'Golf', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Audi', 'R8', 'Vollaustattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Mini', 'Cooper', 'Minimale Ausstattung');
INSERT INTO T_CARS (marke, modell, ausstattung) VALUES ('Tesla', 'Model X', 'Vollaustattung');

/* --------------------
   T_PERSONEN
*/ --------------------

-- create
CREATE TABLE T_PERSONEN(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vorname VARCHAR2(64) NOT NULL,
    nachname VARCHAR2(64) NOT NULL,
    geburtsdatum DATE NOT NULL,
    fuehrerschein_valid CHAR(1) NOT NULL
);

-- empty table
DELETE T_PERSONEN;

-- insert
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Thomas', 'Fankhauser',to_date('01/05/1999', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Fabian', 'Geistert', to_date('08/09/1997', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Thomas', 'Macek', to_date('11/03/1989', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Gregor', 'Holli',to_date('28/02/1998', 'dd/mm/yyyy'), 'n');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'A',to_date('01/01/1970', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'B', to_date('02/01/1971', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'C', to_date('03/02/1972', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'D',to_date('04/02/1973', 'dd/mm/yyyy'), 'n');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'E',to_date('05/03/1974', 'dd/mm/yyyy'), 'y');
INSERT INTO T_PERSONEN (vorname, nachname, geburtsdatum, fuehrerschein_valid) VALUES ('Person', 'F', to_date('06/03/1975', 'dd/mm/yyyy'), 'n');

/* --------------------
   T_KUNDEN
*/ --------------------

-- create
CREATE TABLE T_KUNDEN(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_fk NUMBER REFERENCES T_PERSONEN(id) NOT NULL,
    adresse_fk NUMBER REFERENCES T_ADRESSEN(id) NOT NULL,
    stammkunde CHAR(1) NOT NULL
);

-- empty table
DELETE T_KUNDEN;

-- insert
INSERT INTO T_KUNDEN (person_fk, adresse_fk, stammkunde) VALUES (1,1,'y');
INSERT INTO T_KUNDEN (person_fk, adresse_fk, stammkunde) VALUES (2,2,'y');
INSERT INTO T_KUNDEN (person_fk, adresse_fk, stammkunde) VALUES (3,3,'n');
INSERT INTO T_KUNDEN (person_fk, adresse_fk, stammkunde) VALUES (4,4,'n');
INSERT INTO T_KUNDEN (person_fk, adresse_fk, stammkunde) VALUES (5,5,'n');

/* --------------------
   T_STANDORTE
*/ --------------------

-- create
CREATE TABLE T_STANDORTE(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresse_fk NUMBER REFERENCES T_ADRESSEN(id) NOT NULL
);

-- empty table
DELETE T_STANDORTE;

-- insert
INSERT INTO T_STANDORTE (adresse_fk) VALUES (1);
INSERT INTO T_STANDORTE (adresse_fk) VALUES (2);
INSERT INTO T_STANDORTE (adresse_fk) VALUES (8);
INSERT INTO T_STANDORTE (adresse_fk) VALUES (9);

/* --------------------
   T_MITARBEITER
*/ --------------------

-- create
CREATE TABLE T_MITARBEITER(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_fk NUMBER REFERENCES T_PERSONEN(id) NOT NULL,
    standort_fk NUMBER REFERENCES T_ADRESSEN(id) NOT NULL,
    gehalt NUMBER NOT NULL
);

-- empty table
DELETE T_MITARBEITER;

-- insert
INSERT INTO T_MITARBEITER (person_fk, standort_fk, gehalt) VALUES (1, 2, 2430.69);
INSERT INTO T_MITARBEITER (person_fk, standort_fk, gehalt) VALUES (2, 1, 1030.30);

/* --------------------
   T_PREISE
*/ --------------------

-- create
CREATE TABLE T_PREISE(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    car_fk NUMBER REFERENCES T_CARS(id) NOT NULL,
    preis NUMBER NOT NULL
);

-- empty table
DELETE T_PREISE;

-- insert
INSERT INTO T_PREISE (car_fk, preis) VALUES (1,10);
INSERT INTO T_PREISE (car_fk, preis) VALUES (2,15);
INSERT INTO T_PREISE (car_fk, preis) VALUES (3,25);
INSERT INTO T_PREISE (car_fk, preis) VALUES (4,50);
INSERT INTO T_PREISE (car_fk, preis) VALUES (5,13.50);

/* --------------------
   T_SCHAEDEN
*/ --------------------

-- create
CREATE TABLE T_SCHAEDEN(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_fk NUMBER REFERENCES T_CARS(id) NOT NULL,
    schaden VARCHAR2(256) NOT NULL,
    datum DATE NOT NULL,
    repariert_datum DATE NULL
);

-- empty table
DELETE T_SCHAEDEN;

-- insert
INSERT INTO T_SCHAEDEN (car_fk, schaden, datum, repariert_datum) VALUES (2, 'Stossstange eingedrueckt, Licht beschaedigt', to_date('23/12/2019', 'dd-mm-yyyy'), NULL);
INSERT INTO T_SCHAEDEN (car_fk, schaden, datum, repariert_datum) VALUES (6, 'Raucher im Innenraum', to_date('20/04/2018', 'dd-mm-yyyy'), to_date('05/06/2018', 'dd-mm-yyyy'));

/* --------------------
   T_VERFUEGBARKEIT
*/ --------------------

-- create
CREATE TABLE T_VERFUEGBARKEIT(
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   car_fk NUMBER REFERENCES T_CARS(id) NOT NULL,
   standort_fk NUMBER REFERENCES T_STANDORTE(id) NOT NULL,
   verfuegbar CHAR(1) NOT NULL
);

-- empty table
DELETE T_VERFUEGBARKEIT;

-- insert
INSERT INTO T_VERFUEGBARKEIT (car_fk, standort_fk, verfuegbar) VALUES (1,1,'y');
INSERT INTO T_VERFUEGBARKEIT (car_fk, standort_fk, verfuegbar) VALUES (2,1,'n');
INSERT INTO T_VERFUEGBARKEIT (car_fk, standort_fk, verfuegbar) VALUES (3,2,'y');
INSERT INTO T_VERFUEGBARKEIT (car_fk, standort_fk, verfuegbar) VALUES (4,3,'y');
INSERT INTO T_VERFUEGBARKEIT (car_fk, standort_fk, verfuegbar) VALUES (5,3,'y');

/* --------------------
   T_BUCHUNGEN
*/ --------------------

-- create
CREATE TABLE T_BUCHUNGEN(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kunde_fk NUMBER REFERENCES T_KUNDEN(id) NOT NULL,
    standort_fk NUMBER REFERENCES T_STANDORTE(id) NOT NULL,
    car_fk NUMBER REFERENCES T_CARS(id) NOT NULL,
    datum_von DATE NOT NULL,
    datum_bis DATE NOT NULL,
    summe NUMBER NOT NULL
);

-- empty table
DELETE T_BUCHUNGEN;

-- insert
INSERT INTO T_BUCHUNGEN (kunde_fk, standort_fk, car_fk, datum_von, datum_bis, summe) VALUES (1,2,3,to_date('01/05/2019', 'dd/mm/yyyy'),to_date('03/05/2019', 'dd/mm/yyyy'), 0);

COMMIT;