-- create
CREATE TABLE T_STANDORTE(
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    adresse_fk NUMBER REFERENCES T_ADRESSEN(id) NOT NULL
);

-- empty table
DELETE T_STANDORTE;

-- insert
INSERT INTO T_STANDORTE (id, adresse) VALUES (1,1);
INSERT INTO T_STANDORTE (id, adresse) VALUES (2,2);
INSERT INTO T_STANDORTE (id, adresse) VALUES (3,8);
INSERT INTO T_STANDORTE (id, adresse) VALUES (4,9);
