CREATE TABLE T_CARS(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    marke VARCHAR2(50) NOT NULL,
    modell VARCHAR2(50) NOT NULL,
    preisklasse int NOT NULL
);

delete T_CARS;

INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('VW', 'Jetta', 2);
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Mercedes', 'A45 AMG', 1);
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Mercedes', 'C63', 1);
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Audi', 'A8', 1);
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('Ford', 'Focus', 3);
INSERT INTO T_CARS (marke, modell, preisklasse) VALUES ('VW', 'Polo', 3);


