CREATE TABLE T_PREISKLASSEN(
    id NUMBER GENERATED ALWAYS AS IDENTITY,

    preis float NOT NULL
);

delete T_PREISKLASSEN;

INSERT INTO T_PREISKLASSEN (preis) VALUES (10);
INSERT INTO T_PREISKLASSEN (preis) VALUES (15);
INSERT INTO T_PREISKLASSEN (preis) VALUES (25);
INSERT INTO T_PREISKLASSEN (preis) VALUES (50);
INSERT INTO T_PREISKLASSEN (preis) VALUES (13.50);
INSERT INTO T_PREISKLASSEN (preis) VALUES (20);


